// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/api/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_218cb65e2270ee12, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_218cb65e2270ee12, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UpdateUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_218cb65e2270ee12, []int{2}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type DeleteUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_218cb65e2270ee12, []int{3}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_218cb65e2270ee12, []int{4}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "user.UserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
}

func init() {
	proto.RegisterFile("internal/api/user/user.proto", fileDescriptor_218cb65e2270ee12)
}

var fileDescriptor_218cb65e2270ee12 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0x3b, 0x31,
	0x10, 0xc6, 0xe9, 0xfe, 0xfb, 0x6f, 0xed, 0x28, 0x85, 0x8e, 0x95, 0x96, 0x2a, 0x22, 0xb9, 0xa8,
	0x45, 0xba, 0xa8, 0x07, 0xc1, 0xa3, 0x0a, 0xd2, 0x9b, 0x56, 0x5a, 0xd0, 0x8b, 0x44, 0x3b, 0x94,
	0xc0, 0x36, 0x59, 0x93, 0xb4, 0x17, 0xf1, 0xe2, 0x2b, 0xf8, 0x68, 0x9e, 0xbd, 0xf9, 0x20, 0xb2,
	0xc9, 0xda, 0xae, 0xba, 0x48, 0x0f, 0x5e, 0x96, 0xc9, 0x30, 0xdf, 0x6f, 0xbf, 0xcc, 0x17, 0xd8,
	0x10, 0xd2, 0x92, 0x96, 0x3c, 0x0a, 0x79, 0x2c, 0xc2, 0x89, 0x21, 0xed, 0x3e, 0x9d, 0x58, 0x2b,
	0xab, 0xb0, 0x98, 0xd4, 0xad, 0xed, 0x91, 0x52, 0xa3, 0x88, 0x78, 0x2c, 0x4c, 0xe8, 0x4b, 0x37,
	0xcc, 0xa5, 0x54, 0x96, 0x5b, 0xa1, 0xa4, 0xf1, 0xe3, 0xec, 0x08, 0x96, 0xfb, 0x86, 0x74, 0x8f,
	0x1e, 0x26, 0x64, 0x2c, 0x22, 0x14, 0x25, 0x1f, 0x53, 0xb3, 0xb0, 0x55, 0xd8, 0xa9, 0xf4, 0x5c,
	0x8d, 0x75, 0xf8, 0x4f, 0x63, 0x2e, 0xa2, 0x66, 0xe0, 0x9a, 0xfe, 0xc0, 0x76, 0xa1, 0x7a, 0x4e,
	0x36, 0xab, 0x6d, 0x40, 0x39, 0xf9, 0xf7, 0xad, 0x18, 0xa6, 0xf2, 0x52, 0x72, 0xec, 0x0e, 0xd9,
	0x00, 0x6a, 0xfd, 0x78, 0xc8, 0x2d, 0x2d, 0x32, 0x3d, 0xb3, 0x10, 0xe4, 0x59, 0xf8, 0x97, 0xb5,
	0xb0, 0x07, 0xb5, 0x33, 0x8a, 0x68, 0x31, 0x2e, 0xbb, 0x84, 0x15, 0x3f, 0x67, 0x62, 0x25, 0x0d,
	0xfd, 0x81, 0x81, 0x83, 0xb7, 0xc0, 0x6f, 0xef, 0x8a, 0xf4, 0x54, 0xdc, 0x13, 0x76, 0x01, 0x4e,
	0x35, 0xa5, 0x17, 0xc5, 0x5a, 0xc7, 0xc5, 0x92, 0x31, 0xd7, 0xc2, 0x6c, 0xcb, 0xfb, 0x60, 0xf5,
	0xe7, 0xd7, 0xf7, 0x97, 0xa0, 0xca, 0x2a, 0xe1, 0x74, 0xdf, 0x05, 0x69, 0x8e, 0x0b, 0x6d, 0xbc,
	0x80, 0x72, 0xba, 0x5e, 0xac, 0x7b, 0xd1, 0xd7, 0x6d, 0xe7, 0xa2, 0xd6, 0x1d, 0x6a, 0x0d, 0x57,
	0x67, 0xa8, 0xf0, 0x31, 0xbd, 0xe3, 0x13, 0x5e, 0x03, 0xcc, 0x53, 0xc0, 0x46, 0x2a, 0xff, 0x9e,
	0x4b, 0x2e, 0x77, 0xd3, 0x71, 0x9b, 0xad, 0x3c, 0x6e, 0x62, 0x76, 0x00, 0x30, 0x0f, 0xe2, 0x13,
	0xfd, 0x23, 0x9a, 0xdf, 0x2c, 0xb7, 0xf3, 0xd0, 0x27, 0x4b, 0x37, 0xa5, 0x8e, 0x6b, 0xde, 0x95,
	0xdc, 0x6b, 0x3d, 0xfc, 0x08, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x79, 0x4d, 0x39, 0xfc, 0x02, 0x00,
	0x00,
}
