services:
  otel-collector:
    image: otel/opentelemetry-collector
    ports:
      - "4317:4317"  # For traces
      - "55680:55680"  # For metrics
    networks:
      - otlp

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
    networks:
      - otlp
    depends_on:
      - otel-collector

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - otlp
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  otlp:

